/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistantRole;

import Business.Appointment.Appointment;
import Business.Appointment.AppointmentDirectory;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.VitalSigns.VitalSign;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    HospitalEnterprise enterprise;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    Employee employee;
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,Enterprise enterprise, LabTestWorkRequest request,Employee employee) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.employee=employee;
        this.enterprise=(HospitalEnterprise)enterprise;
//        patientnameTxtFld.setText(request.getPatient().getPatientID());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        patientNameLabel = new javax.swing.JLabel();
        patientnameTxtFld = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        T3TxtFld = new javax.swing.JTextField();
        T4TxtFld = new javax.swing.JTextField();
        TSHTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        testResultTxtFld = new javax.swing.JTextField();
        thyroidTestLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        haemoglobinTxtFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        wbcTxtFld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bloodSugarTxtFld = new javax.swing.JTextField();

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        patientNameLabel.setText("Patient name:");

        jLabel1.setText("T3:");

        jLabel2.setText("T4:");

        jLabel3.setText("TSH:");

        jLabel4.setText("Test Result:");

        thyroidTestLabel.setText("Thyroid Effects");

        jLabel5.setText("Other tests");

        jLabel6.setText("Haemoglobin:");

        jLabel7.setText("WBC Count");

        jLabel8.setText("Bllood Sugar Levels:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(patientNameLabel)
                        .addGap(30, 30, 30)
                        .addComponent(patientnameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TSHTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(T4TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(T3TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(259, 259, 259)
                                .addComponent(submitJButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(32, 32, 32)
                                    .addComponent(testResultTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(haemoglobinTxtFld)
                                        .addComponent(wbcTxtFld)
                                        .addComponent(bloodSugarTxtFld))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(thyroidTestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel5)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientnameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thyroidTestLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(T3TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T4TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TSHTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(haemoglobinTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(wbcTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bloodSugarTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(testResultTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
       
        //if statement to validate the vital sign entries
        
       
           boolean isValid = true;
           String T3 = T3TxtFld.getText();
        if (T3.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "T3 cannot be empty", "Error", messageType);
            T3TxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            T3TxtFld.setBackground(Color.white);
        }
        String T4 = T4TxtFld.getText();
        if (T4.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "T4 cannot be empty", "Error", messageType);
            T4TxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            T4TxtFld.setBackground(Color.white);
        }
        String TSH = TSHTxtFld.getText();
        if (TSH.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "TSH cannot be empty", "Error", messageType);
            TSHTxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            T4TxtFld.setBackground(Color.white);
        }
        String hemoglobin = haemoglobinTxtFld.getText();
        if (hemoglobin.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "Hemoglobin cannot be empty", "Error", messageType);
            haemoglobinTxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            haemoglobinTxtFld.setBackground(Color.white);
        }
        String WBC = wbcTxtFld.getText();
        if (WBC.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "WBC count cannot be empty", "Error", messageType);
            wbcTxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            wbcTxtFld.setBackground(Color.white);
        }
        String bloodSugar= bloodSugarTxtFld.getText();
        if (bloodSugar.isEmpty()) {
            int messageType = JOptionPane.ERROR_MESSAGE;
            JOptionPane.showMessageDialog(null, "Blood Sugar cannot be empty", "Error", messageType);
            bloodSugarTxtFld.setBackground(Color.red);
            isValid = false;
        } else {
            bloodSugarTxtFld.setBackground(Color.white);
        }
        
        
        //finaally submitting the values to the request
        if(isValid)
        {
        VitalSign vs=new VitalSign();
        vs.setTestedBy(employee);
        vs.setT3(Double.parseDouble(T3TxtFld.getText()));
        vs.setT4(Double.parseDouble(T4TxtFld.getText()));
       vs.setTsh(Double.parseDouble(TSHTxtFld.getText()));
        vs.setBloodSugar(Double.parseDouble(bloodSugarTxtFld.getText()));
        vs.setHaemoglobin(Double.parseDouble(haemoglobinTxtFld.getText()));
        vs.setWbcCount(Double.parseDouble(wbcTxtFld.getText()));
        vs.setStatus(testResultTxtFld.getText());
        vs.setReportId(request.getPatientAppointment().getAppointmentId());
        enterprise.searchForAppointment(vs.getReportId()).setReportTestedBy(employee);
        System.out.println("repord id:"+vs.getReportId());
//        System.out.println("Patient name: "+request.getPatient().getFirstName());
        
        request.getPatient().getVitalSignHistory().addVitalSign(vs);
       
        request.setTestResult(testResultTxtFld.getText());
        request.setStatus("Completed");
          JOptionPane.showMessageDialog(null, "Test Result Submitted Successfully!!!");
          testResultTxtFld.setText("");
          wbcTxtFld.setText("");
          haemoglobinTxtFld.setText("");
          bloodSugarTxtFld.setText("");
          TSHTxtFld.setText("");
          T4TxtFld.setText("");
          T3TxtFld.setText("");
          patientnameTxtFld.setText("");
                            
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T3TxtFld;
    private javax.swing.JTextField T4TxtFld;
    private javax.swing.JTextField TSHTxtFld;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodSugarTxtFld;
    private javax.swing.JTextField haemoglobinTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JTextField patientnameTxtFld;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField testResultTxtFld;
    private javax.swing.JLabel thyroidTestLabel;
    private javax.swing.JTextField wbcTxtFld;
    // End of variables declaration//GEN-END:variables
}
