/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdministrativeRole;

import Business.Enterprise.Enterprise;
import static Business.Organization.Organization.Type.Patient;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chand
 */
public class AddNewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewPatient
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    String familyHistory=new String("");
    public AddNewPatientJPanel(JPanel userprocessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userprocessContainer;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPatientBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        personalDetailPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstNameTxtFld = new javax.swing.JTextField();
        lastNameTxtFld = new javax.swing.JTextField();
        phoneNumTxtFld = new javax.swing.JTextField();
        emailTxtFld = new javax.swing.JTextField();
        ageTxtFld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxtaRea = new javax.swing.JTextArea();
        patientDetailsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        smokerRadioBtn = new javax.swing.JRadioButton();
        NonSmokerRadioBtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        DiabeticRadioBtn = new javax.swing.JRadioButton();
        NotDiabeticRadioBtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        sevenRadioBtn = new javax.swing.JRadioButton();
        fourRadioBtn = new javax.swing.JRadioButton();
        threehrRadioBtn = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        MotherCheckBox = new javax.swing.JCheckBox();
        FatherCheckBox = new javax.swing.JCheckBox();
        SiblingsCheckBox = new javax.swing.JCheckBox();

        addPatientBtn.setText("Add Patient");
        addPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Patients Personal Details");

        jLabel12.setText("Enter Patient Habits");

        personalDetailPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("First Name:");

        jLabel3.setText("Lastname:");

        jLabel4.setText("Phone :");

        jLabel5.setText("Email Id:");

        jLabel6.setText("Address:");

        jLabel8.setText("Age:");

        addressTxtaRea.setColumns(20);
        addressTxtaRea.setRows(5);
        jScrollPane1.setViewportView(addressTxtaRea);

        javax.swing.GroupLayout personalDetailPanelLayout = new javax.swing.GroupLayout(personalDetailPanel);
        personalDetailPanel.setLayout(personalDetailPanelLayout);
        personalDetailPanelLayout.setHorizontalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(ageTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalDetailPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(emailTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(phoneNumTxtFld)
                            .addComponent(lastNameTxtFld)
                            .addComponent(firstNameTxtFld))))
                .addContainerGap())
        );
        personalDetailPanelLayout.setVerticalGroup(
            personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ageTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        patientDetailsPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("Smoking Habit:");

        smokerRadioBtn.setText("Smoker");
        smokerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smokerRadioBtnActionPerformed(evt);
            }
        });

        NonSmokerRadioBtn.setText("Non-Smoker");
        NonSmokerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonSmokerRadioBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Diabetes:");

        DiabeticRadioBtn.setText("Diabetic");
        DiabeticRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiabeticRadioBtnActionPerformed(evt);
            }
        });

        NotDiabeticRadioBtn.setText("Not Diabetic");
        NotDiabeticRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotDiabeticRadioBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Work Out Status (per week)");

        sevenRadioBtn.setText("7-8 hours ");
        sevenRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenRadioBtnActionPerformed(evt);
            }
        });

        fourRadioBtn.setText("4-6 hours");
        fourRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourRadioBtnActionPerformed(evt);
            }
        });

        threehrRadioBtn.setText("1-3 hours");
        threehrRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threehrRadioBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Family History ");

        MotherCheckBox.setText("Mother");
        MotherCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherCheckBoxActionPerformed(evt);
            }
        });

        FatherCheckBox.setText("Father");
        FatherCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherCheckBoxActionPerformed(evt);
            }
        });

        SiblingsCheckBox.setText("Siblings");
        SiblingsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiblingsCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientDetailsPanelLayout = new javax.swing.GroupLayout(patientDetailsPanel);
        patientDetailsPanel.setLayout(patientDetailsPanelLayout);
        patientDetailsPanelLayout.setHorizontalGroup(
            patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel9)
                            .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(threehrRadioBtn))
                                    .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(MotherCheckBox)
                                        .addComponent(jLabel13)))
                                .addGap(40, 40, 40)
                                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fourRadioBtn)
                                    .addComponent(FatherCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SiblingsCheckBox)
                                    .addComponent(sevenRadioBtn)))))
                    .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(smokerRadioBtn)
                            .addComponent(DiabeticRadioBtn))
                        .addGap(49, 49, 49)
                        .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NonSmokerRadioBtn)
                            .addComponent(NotDiabeticRadioBtn))))
                .addGap(25, 25, 25))
        );
        patientDetailsPanelLayout.setVerticalGroup(
            patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smokerRadioBtn)
                    .addComponent(NonSmokerRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiabeticRadioBtn)
                    .addComponent(NotDiabeticRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threehrRadioBtn)
                    .addComponent(fourRadioBtn)
                    .addComponent(sevenRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(patientDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotherCheckBox)
                    .addComponent(FatherCheckBox)
                    .addComponent(SiblingsCheckBox))
                .addGap(206, 206, 206))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPatientBtn)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(238, 238, 238)
                        .addComponent(jLabel12)
                        .addContainerGap(289, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(personalDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(patientDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addPatientBtn))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(patientDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(personalDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        // TODO add your handling code here:
        PatientOrganization organization=(PatientOrganization)enterprise.getOrganizationDirectory().searchOrganization("Patient Organization");
        //check if data is not null
        
        //and then new patient is created and added to the list
        Patient patient=new Patient(enterprise.getName(),firstNameTxtFld.getText(),organization.getPatientDiretcory().getPatientList().size());
        
        //assign personal details
        patient.setFirstName(firstNameTxtFld.getText());
        patient.setLastName(lastNameTxtFld.getText());
        patient.setAddress(addressTxtaRea.getText());
        patient.setAge(Integer.parseInt(ageTxtFld.getText()));
        
        
        


        AddPatientUserAccountJPanel addNewPatientUAPanel = new AddPatientUserAccountJPanel(userProcessContainer,patient,enterprise,organization);
        userProcessContainer.add("addNewPatientUserAccount",addNewPatientUAPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void smokerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smokerRadioBtnActionPerformed
        // TODO add your handling code here:
        if (smokerRadioBtn.isSelected())
        {

            NonSmokerRadioBtn.setSelected(false);

        }
    }//GEN-LAST:event_smokerRadioBtnActionPerformed

    private void NonSmokerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonSmokerRadioBtnActionPerformed
        // TODO add your handling code here:
        if (NonSmokerRadioBtn.isSelected())
        {

            smokerRadioBtn.setSelected(false);

        }
    }//GEN-LAST:event_NonSmokerRadioBtnActionPerformed

    private void DiabeticRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiabeticRadioBtnActionPerformed
        // TODO add your handling code here:
        if (DiabeticRadioBtn.isSelected())
        {

            NotDiabeticRadioBtn.setSelected(false);

        }
    }//GEN-LAST:event_DiabeticRadioBtnActionPerformed

    private void NotDiabeticRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotDiabeticRadioBtnActionPerformed
        // TODO add your handling code here:
        if (NotDiabeticRadioBtn.isSelected())
        {

            DiabeticRadioBtn.setSelected(false);

        }
    }//GEN-LAST:event_NotDiabeticRadioBtnActionPerformed

    private void sevenRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenRadioBtnActionPerformed
        // TODO add your handling code here:
        if (sevenRadioBtn.isSelected()) {

            fourRadioBtn.setSelected(false);
            threehrRadioBtn.setSelected(false);

        }
    }//GEN-LAST:event_sevenRadioBtnActionPerformed

    private void fourRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourRadioBtnActionPerformed
        // TODO add your handling code here:
        if (fourRadioBtn.isSelected()) {
            sevenRadioBtn.setSelected(false);
            threehrRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_fourRadioBtnActionPerformed

    private void threehrRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threehrRadioBtnActionPerformed
        // TODO add your handling code here:
        if (threehrRadioBtn.isSelected()) {
            fourRadioBtn.setSelected(false);
            sevenRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_threehrRadioBtnActionPerformed

    private void MotherCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherCheckBoxActionPerformed
        // TODO add your handling code here:
        if (MotherCheckBox.isSelected()) {
            familyHistory = familyHistory.concat(",").concat(MotherCheckBox.getText());
        }
    }//GEN-LAST:event_MotherCheckBoxActionPerformed

    private void FatherCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherCheckBoxActionPerformed
        // TODO add your handling code here:
        if (FatherCheckBox.isSelected()) {
            familyHistory = familyHistory.concat(",").concat(FatherCheckBox.getText());
        }
    }//GEN-LAST:event_FatherCheckBoxActionPerformed

    private void SiblingsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiblingsCheckBoxActionPerformed
        // TODO add your handling code here:
        if (SiblingsCheckBox.isSelected()) {
            familyHistory = familyHistory.concat(",").concat(SiblingsCheckBox.getText());
        }
    }//GEN-LAST:event_SiblingsCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DiabeticRadioBtn;
    private javax.swing.JCheckBox FatherCheckBox;
    private javax.swing.JCheckBox MotherCheckBox;
    private javax.swing.JRadioButton NonSmokerRadioBtn;
    private javax.swing.JRadioButton NotDiabeticRadioBtn;
    private javax.swing.JCheckBox SiblingsCheckBox;
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JTextArea addressTxtaRea;
    private javax.swing.JTextField ageTxtFld;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JTextField firstNameTxtFld;
    private javax.swing.JRadioButton fourRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxtFld;
    private javax.swing.JPanel patientDetailsPanel;
    private javax.swing.JPanel personalDetailPanel;
    private javax.swing.JTextField phoneNumTxtFld;
    private javax.swing.JRadioButton sevenRadioBtn;
    private javax.swing.JRadioButton smokerRadioBtn;
    private javax.swing.JRadioButton threehrRadioBtn;
    // End of variables declaration//GEN-END:variables
}
