/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Appointment.Appointment;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.SchedulerOrganization;
import Business.UserAccount.PatientUserAccount;
import Business.VitalSigns.VitalSign;
import Business.VitalSigns.VitalSignHistory;
import Business.WorkQueue.AppointmentWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author chand
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    JPanel userProcessContainer;
    PatientOrganization organization;
    PatientUserAccount userAccount;
    Enterprise enterprise;
    public PatientWorkAreaJPanel(JPanel userProcessContainer,PatientUserAccount userAccount,PatientOrganization organization,Enterprise enterprise) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        this.enterprise=enterprise;
        patientnameLabel.setText(userAccount.getPatient().getFirstName());
        populateDoctorCombo();
        populateAppointmentTable();
        populateReportTable();
       
         Main main1=new Main(populatet3Dataset(userAccount.getPatient().getVitalSignHistory()),"T3 Level");
       ChartPanel chartPanel1=main1.pushChartPanel();
      // targetPanel.removeAll();
      Main main2=new Main(populatet4Dataset(userAccount.getPatient().getVitalSignHistory()),"T4 Level");
        t3Panel.add(chartPanel1);
        ChartPanel chartPanel2=main2.pushChartPanel();
        t4Panel.add(chartPanel2);
        Main main3=new Main(populatetshDataset(userAccount.getPatient().getVitalSignHistory()),"TSH Level");
            ChartPanel chartPanel3=main3.pushChartPanel();
        tshPanel.add(chartPanel3);
        Main main4=new Main(populateSugarDataset(userAccount.getPatient().getVitalSignHistory()),"Blood Sugar Level");
        ChartPanel chartPanel4=main4.pushChartPanel();
        sugarLevel.add(chartPanel4);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        patientnameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lastAppointmentDateTxtFld = new javax.swing.JTextField();
        nextAppointmentTxtFld = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        reportsPanel = new javax.swing.JPanel();
        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportsTable = new javax.swing.JTable();
        viewReportButton = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        scheduleAppointmentPanel = new javax.swing.JPanel();
        scheduleAppointmentLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        appointmentReasonCombo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        doctorListCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        AppointmentsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstnameTxtFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        t3Panel = new javax.swing.JPanel();
        t4Panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        tshPanel = new javax.swing.JPanel();
        sugarLevel = new javax.swing.JPanel();

        jSplitPane1.setBackground(new java.awt.Color(255, 102, 102));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(835, 100));

        patientnameLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        patientnameLabel.setForeground(new java.awt.Color(255, 51, 51));
        patientnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientnameLabel.setText("Hello <Patient Name>!!!!");

        jLabel10.setText("Last Scheduled Appointment was ON:");

        jLabel11.setText("Next Sceduled Appointment is ON:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastAppointmentDateTxtFld)
                    .addComponent(nextAppointmentTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lastAppointmentDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(nextAppointmentTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(100, 120));

        reportsPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportsPanel.setLayout(new java.awt.CardLayout());

        reportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Report Id", "Test conducted on", "Status", "Seen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportsTable.setSelectionBackground(new java.awt.Color(153, 255, 102));
        reportsTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        reportsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(reportsTable);

        viewReportButton.setText("View this Report");
        viewReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportButtonActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewReportButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewReportButton)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        reportsPanel.add(viewPanel, "card5");

        jTabbedPane1.addTab("My Reports", reportsPanel);

        scheduleAppointmentPanel.setBackground(new java.awt.Color(255, 255, 255));

        scheduleAppointmentLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        scheduleAppointmentLabel.setForeground(new java.awt.Color(255, 0, 0));
        scheduleAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleAppointmentLabel.setText("Schedule an Appointment");

        jLabel12.setText("Reason for your appointment:");

        appointmentReasonCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Appointment", "Emergency Due to drug infection", "Appointment prepone due to emergency", "Appointment postpone due to emergency" }));

        jButton3.setText("Request Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        doctorListCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("With Doctor:");

        javax.swing.GroupLayout scheduleAppointmentPanelLayout = new javax.swing.GroupLayout(scheduleAppointmentPanel);
        scheduleAppointmentPanel.setLayout(scheduleAppointmentPanelLayout);
        scheduleAppointmentPanelLayout.setHorizontalGroup(
            scheduleAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleAppointmentPanelLayout.createSequentialGroup()
                .addContainerGap(505, Short.MAX_VALUE)
                .addComponent(scheduleAppointmentLabel)
                .addGap(363, 363, 363))
            .addGroup(scheduleAppointmentPanelLayout.createSequentialGroup()
                .addGroup(scheduleAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scheduleAppointmentPanelLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jButton3))
                    .addGroup(scheduleAppointmentPanelLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(scheduleAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(scheduleAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(appointmentReasonCombo, 0, 348, Short.MAX_VALUE)
                                .addComponent(doctorListCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scheduleAppointmentPanelLayout.setVerticalGroup(
            scheduleAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleAppointmentPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scheduleAppointmentLabel)
                .addGap(133, 133, 133)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(appointmentReasonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(doctorListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Schedule Appointment", scheduleAppointmentPanel);

        appointmentTable.setForeground(new java.awt.Color(255, 51, 51));
        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Appointment Id", "Appointment Date", "Doctor", "patient"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(appointmentTable);

        jButton4.setText("View Appointment Details");

        javax.swing.GroupLayout AppointmentsPanelLayout = new javax.swing.GroupLayout(AppointmentsPanel);
        AppointmentsPanel.setLayout(AppointmentsPanelLayout);
        AppointmentsPanelLayout.setHorizontalGroup(
            AppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentsPanelLayout.createSequentialGroup()
                .addGroup(AppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppointmentsPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AppointmentsPanelLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jButton4)))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        AppointmentsPanelLayout.setVerticalGroup(
            AppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentsPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton4)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Appointments", AppointmentsPanel);

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel4.setText("Email id:");

        jLabel5.setText("Address:");

        jLabel6.setText("Age:");

        jLabel7.setText("Date of Birth:");

        jLabel8.setText("Gender:");

        jLabel9.setText("Occupation:");

        pictureLabel.setText("pictureLabel");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(profilePanelLayout.createSequentialGroup()
                                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(48, 48, 48)
                                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField7)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                                .addGroup(profilePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(29, 29, 29)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(49, 49, 49)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGap(92, 92, 92)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(25, 25, 25)))
                        .addGap(39, 39, 39)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(firstnameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(414, 414, 414)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", profilePanel);

        jSplitPane2.setBorder(null);
        jSplitPane2.setDividerLocation(500);

        jSplitPane3.setDividerLocation(250);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        t3Panel.setBackground(new java.awt.Color(255, 255, 204));
        t3Panel.setLayout(new java.awt.BorderLayout());
        jSplitPane3.setLeftComponent(t3Panel);

        t4Panel.setBackground(new java.awt.Color(204, 255, 204));
        t4Panel.setLayout(new java.awt.BorderLayout());
        jSplitPane3.setRightComponent(t4Panel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel4);

        jSplitPane4.setDividerLocation(250);
        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tshPanel.setBackground(new java.awt.Color(204, 204, 255));
        tshPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane4.setTopComponent(tshPanel);

        sugarLevel.setBackground(new java.awt.Color(204, 255, 255));
        sugarLevel.setLayout(new java.awt.BorderLayout());
        jSplitPane4.setRightComponent(sugarLevel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jSplitPane2.setRightComponent(jPanel5);

        jTabbedPane1.addTab("Recovery Analysis", jSplitPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1136, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static DefaultCategoryDataset populatet3Dataset(VitalSignHistory vsh)
            {
                DefaultCategoryDataset dataset=new DefaultCategoryDataset();
                for(VitalSign vs:vsh.getVitalSignList())
                {
                dataset.addValue(vs.getT3(),"",vs.getReportId());
                
                }
                return dataset;
            }
    public static DefaultCategoryDataset populatet4Dataset(VitalSignHistory vsh)
            {
                DefaultCategoryDataset dataset=new DefaultCategoryDataset();
                for(VitalSign vs:vsh.getVitalSignList())
                {
                dataset.addValue(vs.getT4(),"",vs.getReportId());
                
                }
                return dataset;
            }
    public static DefaultCategoryDataset populatetshDataset(VitalSignHistory vsh)
            {
                DefaultCategoryDataset dataset=new DefaultCategoryDataset();
                for(VitalSign vs:vsh.getVitalSignList())
                {
                dataset.addValue(vs.getTsh(),"",vs.getReportId());
                
                }
                return dataset;
            }
    public static DefaultCategoryDataset populateSugarDataset(VitalSignHistory vsh)
            {
                DefaultCategoryDataset dataset=new DefaultCategoryDataset();
                for(VitalSign vs:vsh.getVitalSignList())
                {
                dataset.addValue(vs.getBloodSugar(),"",vs.getReportId());
                
                }
                return dataset;
            }
    public void populateReportTable(){
        
        DefaultTableModel model=(DefaultTableModel)reportsTable.getModel();
        
        model.setRowCount(0);
        int numberOfVitalSigns=userAccount.getPatient().getVitalSignHistory().getVitalSignList().size();
        System.out.println("Number of reports: "+numberOfVitalSigns);
        if(numberOfVitalSigns>0)
        {
               for(VitalSign vitalSign:userAccount.getPatient().getVitalSignHistory().getVitalSignList())
                {
                        
                    
                        Object[] row = new Object[4];
                        row[0] = vitalSign;
                        row[1] = getReportDate(vitalSign.getReportId());
                        row[2]=vitalSign.getStatus();
                        row[3]=vitalSign.toString();
            
                        model.addRow(row);
                }
        }
        
        
        
    }
    public Date getReportDate(String reportId)
    {
        Date reportDate=null;
        for(Appointment appointment:userAccount.getPatient().getAppointmentHist())
        {
            if(reportId.equalsIgnoreCase(appointment.getAppointmentId()))
            {
                return appointment.getAppointmentDate();
            }
        }
        return reportDate;
    }
    public void populateAppointmentTable(){
        DefaultTableModel model=(DefaultTableModel)appointmentTable.getModel();
        
        model.setRowCount(0);
        int numberOfAppointments=userAccount.getPatient().getAppointmentHist().size();
        if(numberOfAppointments>0)
        {
               for(Appointment appointment:userAccount.getPatient().getAppointmentHist())
                {
          
                        Object[] row = new Object[4];
                        row[0] = appointment;
                        row[1] = appointment.getAppointmentDate();
                        row[2]=appointment.getAppointmentId();
                        row[3]=appointment.getPatient();
            
                    model.addRow(row);
                }
        }
   
            
        
        
        
    }
    public void populateDoctorCombo(){
        doctorListCombo.removeAllItems();
        
        for(Employee employee:enterprise.getOrganizationDirectory().searchOrganization("Doctor Organization").getEmployeeDirectory().getEmployeeList())
        {
            doctorListCombo.addItem(employee.getName());
        }
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        DateFormat fmt = new SimpleDateFormat("dd/mm/yyyy");
        //String date = fmt.format(jDateChooser1.getDate());
        System.out.println("Chosen date:"+jDateChooser1.getDate());
        String doctorName=doctorListCombo.getSelectedItem().toString();
        if(jDateChooser1.getDate()==null || doctorListCombo.getSelectedItem()==null)
        {
            
        }
        else{
        System.out.println("Doctor selected "+doctorName);
        Employee employee=enterprise.getOrganizationDirectory().searchOrganization("Doctor Organization").getEmployeeDirectory().searchEmployee(doctorListCombo.getSelectedItem().toString());
         String message ="Appointment"+employee.getName();
        
        AppointmentWorkRequest request = new AppointmentWorkRequest();
        //appointment request date
        request.setAppointmentReqDate(jDateChooser1.getDate());
        
        //appointment set doctor
        request.setDoctor(enterprise.getOrganizationDirectory().searchOrganization("Doctor Organization").getEmployeeDirectory().searchEmployee(doctorListCombo.getSelectedItem().toString()));
        System.out.println(request.getDoctor().getName());
        request.setMessage(message);
        
        //appointment sender
        request.setSender(userAccount);
        
        request.setStatus("Sent");
        
        SchedulerOrganization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof SchedulerOrganization){
                org = (SchedulerOrganization)organization;
                break;
            }
        }
        if (org!=null){
            org.getAppointmentWorkQueue().getAppointmentWorkList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            
            for(AppointmentWorkRequest everyrequest:org.getAppointmentWorkQueue().getAppointmentWorkList())
            {
             System.out.println( "Request "+everyrequest.getSender().getUsername());   
            }
        }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void viewReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportButtonActionPerformed
        // TODO add your handling code here:
        int index=reportsTable.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
        else if(index==0||index>0){
        
            System.out.println("I'm here");
            VitalSign vs=(VitalSign)reportsTable.getValueAt(index,0);
        viewReportPanel panel=new viewReportPanel(reportsPanel,userProcessContainer, vs,userAccount,organization,(HospitalEnterprise) enterprise);
         userProcessContainer.add("reporting",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        }
        
    }//GEN-LAST:event_viewReportButtonActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateReportTable();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppointmentsPanel;
    private javax.swing.JComboBox<String> appointmentReasonCombo;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JComboBox<String> doctorListCombo;
    private javax.swing.JTextField firstnameTxtFld;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField lastAppointmentDateTxtFld;
    private javax.swing.JTextField nextAppointmentTxtFld;
    private javax.swing.JLabel patientnameLabel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JTable reportsTable;
    private javax.swing.JLabel scheduleAppointmentLabel;
    private javax.swing.JPanel scheduleAppointmentPanel;
    private javax.swing.JPanel sugarLevel;
    private javax.swing.JPanel t3Panel;
    private javax.swing.JPanel t4Panel;
    private javax.swing.JPanel tshPanel;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JButton viewReportButton;
    // End of variables declaration//GEN-END:variables
}
