/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Enterprise.HospitalEnterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.PatientUserAccount;
import Business.VitalSigns.VitalSign;
import javax.swing.JPanel;

/**
 *
 * @author chand
 */
public class viewReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewReportPanel
     */
    JPanel userProcessContainer;
    VitalSign vitalSign;
    PatientUserAccount userAccount;
    PatientOrganization organization;
    HospitalEnterprise enterprise;
    JPanel reportsPanel;
    public viewReportPanel(JPanel reportsPanel,JPanel userProcessContainer,VitalSign vitalSign,PatientUserAccount userAccount,PatientOrganization organization,HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.vitalSign=vitalSign;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.reportsPanel=reportsPanel;
        System.out.println("I'm in view report panel");
        ViewReportInternalFrame frame=new ViewReportInternalFrame(reportsPanel,userProcessContainer,vitalSign,userAccount, organization,enterprise);
       // reportsPanel.removeAll();
        targetPAnel.add(frame);
        frame.toFront();
        frame.show();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        targetPAnel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 500));

        targetPAnel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(targetPAnel, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(targetPAnel, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel targetPAnel;
    // End of variables declaration//GEN-END:variables
}
