/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Enterprise.HospitalEnterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.PatientUserAccount;
import Business.VitalSigns.VitalSign;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.Charts.DialDemo3;
/**
 *
 * @author chand
 */
public class ViewReportInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewReportInternalFrame
     */
    JPanel userProcessContainer;
    PatientUserAccount userAccount;
    PatientOrganization organization;
    HospitalEnterprise enterprise;
    JPanel reportPanel;
    public ViewReportInternalFrame(JPanel reportsPanel,JPanel userProcessContainer,VitalSign vs,PatientUserAccount userAccount,PatientOrganization organization,HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        System.out.println("I'm in internal frame");
        this.enterprise=enterprise;
        this.reportPanel=reportsPanel;
        DialDemo3 dd=new DialDemo3("Status of the report");
        demoPanel.add(dd);
        dd.setVisible(true);
        reportIdLabel.setText(vs.getReportId());
        t3ValueLabel.setText(String.valueOf(vs.getT3()));
        t4ValueLabel.setText(String.valueOf(vs.getT4()));
        tshvalueLabel.setText(String.valueOf(vs.getTsh()));
        wbccountLabel.setText(String.valueOf(vs.getWbcCount()));
        HaemoglobinValueLabel.setText(String.valueOf(vs.getHaemoglobin()));
        bloodSugarLevelLabel.setText(String.valueOf(vs.getBloodSugar()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reportIdLabel = new javax.swing.JLabel();
        t3Label = new javax.swing.JLabel();
        t3ValueLabel = new javax.swing.JLabel();
        t4jLabel = new javax.swing.JLabel();
        t4ValueLabel = new javax.swing.JLabel();
        tshLabel = new javax.swing.JLabel();
        tshvalueLabel = new javax.swing.JLabel();
        haemoLabel = new javax.swing.JLabel();
        wbcLabel = new javax.swing.JLabel();
        sugarLabel = new javax.swing.JLabel();
        HaemoglobinValueLabel = new javax.swing.JLabel();
        wbccountLabel = new javax.swing.JLabel();
        bloodSugarLevelLabel = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Internal frame");
        addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                formVetoableChange(evt);
            }
        });

        demoPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Report Id:");

        t3Label.setText("T3:");

        t3ValueLabel.setText("T3Value");

        t4jLabel.setText("T4:");

        t4ValueLabel.setText("T4Value");

        tshLabel.setText("TSH:");

        tshvalueLabel.setText("TSHValue");

        haemoLabel.setText("Haemoglobin");

        wbcLabel.setText("WBC Count");

        sugarLabel.setText("Blood Sugar Level");

        HaemoglobinValueLabel.setText("Haemoglobin Value");

        wbccountLabel.setText("WBC Count Value");

        bloodSugarLevelLabel.setText("Blood Sugar Level Value");

        javax.swing.GroupLayout demoPanelLayout = new javax.swing.GroupLayout(demoPanel);
        demoPanel.setLayout(demoPanelLayout);
        demoPanelLayout.setHorizontalGroup(
            demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoPanelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t4jLabel)
                    .addGroup(demoPanelLayout.createSequentialGroup()
                        .addComponent(t3Label)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(reportIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(demoPanelLayout.createSequentialGroup()
                        .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tshLabel)
                            .addComponent(haemoLabel)
                            .addComponent(wbcLabel)
                            .addComponent(sugarLabel))
                        .addGap(50, 50, 50)
                        .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t4ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(t3ValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tshvalueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HaemoglobinValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wbccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bloodSugarLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        demoPanelLayout.setVerticalGroup(
            demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reportIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3ValueLabel)
                    .addComponent(t3Label))
                .addGap(31, 31, 31)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4jLabel)
                    .addComponent(t4ValueLabel))
                .addGap(30, 30, 30)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tshvalueLabel)
                    .addComponent(tshLabel))
                .addGap(34, 34, 34)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haemoLabel)
                    .addComponent(HaemoglobinValueLabel))
                .addGap(37, 37, 37)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wbcLabel)
                    .addComponent(wbccountLabel))
                .addGap(39, 39, 39)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sugarLabel)
                    .addComponent(bloodSugarLevelLabel))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(demoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(demoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_formVetoableChange
        // TODO add your handling code here:
         if (evt.getPropertyName().equals(IS_CLOSED_PROPERTY)) {
         boolean changed = ((Boolean) evt.getNewValue()).booleanValue();
         if (changed) {
             System.out.println("Value changed: "+changed);
             //this.getParent().setVisible(false);
             Component[] componentArray =userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        PatientWorkAreaJPanel panel=new PatientWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise);
//        panel.populateReportTable();
    userProcessContainer.remove(this);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
             
             
         }
         }
        
        
    }//GEN-LAST:event_formVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HaemoglobinValueLabel;
    private javax.swing.JLabel bloodSugarLevelLabel;
    private javax.swing.JPanel demoPanel;
    private javax.swing.JLabel haemoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel reportIdLabel;
    private javax.swing.JLabel sugarLabel;
    private javax.swing.JLabel t3Label;
    private javax.swing.JLabel t3ValueLabel;
    private javax.swing.JLabel t4ValueLabel;
    private javax.swing.JLabel t4jLabel;
    private javax.swing.JLabel tshLabel;
    private javax.swing.JLabel tshvalueLabel;
    private javax.swing.JLabel wbcLabel;
    private javax.swing.JLabel wbccountLabel;
    // End of variables declaration//GEN-END:variables
}
