/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author chand
 */
public class DrugActiveCompoundAnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugActiveCompoundAnalysisPanel
     */
    JPanel userProcessContainer;
    DefaultCategoryDataset dataset;
    public DrugActiveCompoundAnalysisPanel(JPanel userProcessContainer,DefaultCategoryDataset dataset) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.dataset=dataset;
        targetPAnel.add(pushChartPanel());
        
    }

    public ChartPanel pushChartPanel(){
//        int s1=Integer.parseInt(text1.getText());
//        int s2=Integer.parseInt(text2.getText());
//        int s3=Integer.parseInt(text3.getText());
//        int s4=Integer.parseInt(text4.getText());

//        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
//        dataset.setValue(50,"","Section1");
//        dataset.setValue(60,"","Section2");
//        dataset.setValue(70,"","Section3");
//        dataset.setValue(80,"","Section4");

        org.jfree.chart.JFreeChart chart=ChartFactory.createBarChart("Drug Active Compunds", "","", dataset,PlotOrientation.VERTICAL,true,true,true);
        CategoryPlot catPlot=chart.getCategoryPlot();
        catPlot.setRangeGridlinePaint(Color.MAGENTA);

        ChartPanel chartPanel=new ChartPanel(chart);
//        panel.removeAll();
//        panel.add(chartPanel,BorderLayout.CENTER);
        return chartPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        targetPAnel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        targetPAnel.setLayout(new java.awt.BorderLayout());

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(targetPAnel, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(targetPAnel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(0, 67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel targetPAnel;
    // End of variables declaration//GEN-END:variables
}
